# reusable-linters.yml in Felipe-Henrique-morais/governance-scripts
name: Reusable Linters & Formatters
on:
  workflow_call:
    inputs:
      backend-path:
        description: 'Path to the backend service directory'
        required: true
        type: string
      frontend-path:
        description: 'Path to the frontend service directory'
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true

# ... rest of your reusable-linters.yml jobs and steps