# reusable-security.yml in Felipe-Henrique-morais/governance-scripts
name: Reusable Security Checks
on:
  workflow_call:
    inputs:
      backend-path:
        description: 'Path to the backend service directory'
        required: true
        type: string
      frontend-path:
        description: 'Path to the frontend service directory'
        required: true
        type: string
      repo-lower-name: # Add this input as well, if you pass it
        description: 'Lowercase repository name'
        required: false # Set to true if it's always needed
        type: string
    secrets:
      GH_TOKEN:
        required: true

# ... rest of your reusable-security.yml jobs and steps