name: Sign Container Image

on:
  workflow_call:
    inputs:
      image-digest:
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true

jobs:
  sign:
    name: Sign Image
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: read
    steps:
      - name: Install Cosign
        uses: sigstore/cosign-installer@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Sign the image with GitHub OIDC
        run: |
          cosign sign --yes ${{ inputs.image-digest }}